build: false
shallow_clone: true
platform:
  - x86
#  - x64

cache:
  - C:\tools\php -> appveyor.yml

init:
  - SET PATH=C:\tools\php;%PATH%
  - SET COMPOSER_NO_INTERACTION=1
  - SET COMPOSER=0

install:
  - IF EXIST c:\tools\php\composer (SET COMPOSER=1)
  - IF %COMPOSER%==0 cinst -yi php && cinst -y composer -version 4.6.0 -ia /DEV=C:\tools\php
  - IF %COMPOSER%==1 composer self-update 
  - cd %APPVEYOR_BUILD_FOLDER%
  - composer install --prefer-dist --no-progress

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - php test.php
