name: CI-Windows

on: [push]

jobs:
  tests:
    runs-on: windows-latest
    steps:
      env:
        COMPOSER_BINARY: C:\tools\composer
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install Composer
        run: cinst composer -i -y --% --ia /DEV=C:\tools\composer

      - name: Update environment
        run: refreshenv

      - name: Check environment 2
        run: |
          refreshenv
          echo $env:Path

      - name: Check PHP version
        run: php -v

      - name: Check Composer version
        run: $COMPOSER_BINARY --version
