name: CI-Windows

on: [push]

jobs:
  tests:

    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install Composer
        run: cinst composer -i -y --% --ia /DEV=C:\tools\composer

      - name: Update environment
        run: refreshenv

      - name: Check PHP version
        run: php -v

      - name: Check Composer version
        run: composer --version
        shell: cmd

